name: quan_ly_chi_tieu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.67.0
  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  equatable: ^2.0.7
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  flutter_dotenv: ^6.0.0
  cloud_firestore: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo.png
    - assets/images/